<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-10-26 01:17
$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('templavoila');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
    'tx_templavoila_cm1' => $extensionPath . 'cm1/index.php',
    'tx_templavoila_staticds_check' => $extensionClassesPath . 'staticds/class.tx_templavoila_staticds_check.php',
    'tx_templavoila_staticds_wizard' => $extensionClassesPath . 'staticds/class.tx_templavoila_staticds_wizard.php',
    'tx_templavoila_cm1_ajax' => $extensionPath . 'cm1/class.tx_templavoila_cm1_ajax.php',
    'tx_templavoila_cm1_dsedit' => $extensionPath . 'cm1/class.tx_templavoila_cm1_dsedit.php',
    'tx_templavoila_cm1_etypes' => $extensionPath . 'cm1/class.tx_templavoila_cm1_etypes.php',
    'tx_templavoila_cm2' => $extensionPath . 'cm2/index.php',
    'tx_templavoila_module1' => $extensionPath . 'mod1/index.php',
    'tx_templavoila_module2' => $extensionPath . 'mod2/index.php',
    'tx_templavoila_pi1' => $extensionPath . 'pi1/class.tx_templavoila_pi1.php',
    'Extension\Templavoila\Messaging\FlashMessage' => $extensionPath . 'Classes/Messaging/FlashMessage.php',
    'Extension\Templavoila\Controller\NewContentElementController' => $extensionPath . 'Classes/Controller/NewContentElementController.php',
    'Extension\Templavoila\Controller\NewContentElementControllerTypo3Orig' => $extensionPath . 'Classes/Controller/NewContentElementControllerTypo3Orig.php',
    'Extension\Templavoila\Utility\AjayUtility' => $extensionPath . 'Classes/Utility/AjaxUtility.php'
);
